---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "recurring-tasks"
  namespace: "default"
  labels:
    app: "recurring-tasks"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "recurring-tasks"
  template:
    metadata:
      labels:
        app: "recurring-tasks"
    spec:
      containers:
        - name: "recurring-tasks"
          image: "recurring-tasks"
          env:
            - name: NOTION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notion-secrets
                  key: notion-token
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "recurring-tasks-hpa-nkwy"
  namespace: "default"
  labels:
    app: "recurring-tasks"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "recurring-tasks"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 50
